//
//  AuthenticationListXMLImpl.h
//  ecologylabXML
//
//  Generated by CocoaTranslator on 06/16/10.
//  Copyright 2010 Interface Ecology Lab. 
//

#import <Foundation/Foundation.h>
#import "SaverState.h"


/*!
	@class		AuthenticationListXMLImpl
	@abstract	This class is generated by CocoaTranslator. Annotated as: 
				@xml_inherit
	@discussion	missing java doc comments or could not find the source file.
*/
@interface AuthenticationListXMLImpl : SaverState
{
	/*!
		@var		authList
		@abstract	Annotated as : 
					@xml_map
					@xml_scope
		@discussion	missing java doc comments or could not find the source file.
	*/
	NSDictionary *authList;

	/*!
		@var		lastUID
		@abstract	Annotated as : 
					@xml_attribute
		@discussion	missing java doc comments or could not find the source file.
	*/
	long lastUID;

	/*!
		@var		autoSave
		@abstract	Annotated as : 
					@xml_attribute
		@discussion	missing java doc comments or could not find the source file.
	*/
	bool autoSave;

}

@property (nonatomic, readwrite, retain) NSDictionary *authList;
@property (nonatomic, readwrite) long lastUID;
@property (nonatomic, readwrite) bool autoSave;

- (void) setLastUIDWithReference: (long *) p_lastUID;
- (void) setAutoSaveWithReference: (bool *) p_autoSave;

@end

