//
//  ChatUpdate.h
//  ecologylabXML
//
//  Generated by CocoaTranslator on 06/03/10.
//  Copyright 2010 Interface Ecology Lab. 
//

#import <Foundation/Foundation.h>
#import "UpdateMessage.h"

@interface ChatUpdate : UpdateMessage
{
	/*!
	 @var		message
	 @abstract	generated field annotated as  @xml_attribute
	 
	 @discussion	java docs goes here
	 */
	NSString *message;
	
	/*!
	 @var		host
	 @abstract	generated field annotated as @xml_attribute
	 
	 @discussion	java docs goes here
	 */
	NSString *host;
	
	/*!
	 @var		port
	 @abstract	generated field annotated as @xml_attribute
	 
	 @discussion	java docs goes here
	 */
	int port;
	
}

@property (nonatomic, readwrite, retain) NSString *message;
@property (nonatomic, readwrite, retain) NSString *host;
@property (nonatomic, readwrite) int port;

- (void) setPortWithReference: (int *) p_port;

@end


