//
//  BasicOp.m
//  ecologylabXML
//
//  Generated by CocoaTranslator on 08/19/10.
//  Copyright 2010 Interface Ecology Lab. 
//

#import "BasicOp.h"

@implementation BasicOp

@synthesize sessionTime;
- (void) dealloc {
	[super dealloc];
}

- (void) setSessionTimeWithReference: (long *) p_sessionTime {
	sessionTime = *p_sessionTime;
}



@end

