//
//  LogEvent.m
//  ecologylabXML
//
//  Generated by CocoaTranslator on 10/18/10.
//  Copyright 2010 Interface Ecology Lab. 
//

#import "LogEvent.h"

@implementation LogEvent

@synthesize bufferToLog;
- (void) dealloc {
	[bufferToLog release];
	[super dealloc];
}



@end

