//
//  Logging.m
//  ecologylabXML
//
//  Generated by CocoaTranslator on 06/16/10.
//  Copyright 2010 Interface Ecology Lab. 
//

#import "Logging.h"

@implementation Logging

@synthesize opSequence;

+ (void) initialize {
	[Logging class];
}

- (void) dealloc {
	[super dealloc];
}



@end

