//
//  LogOps.m
//  ecologylabXML
//
//  Generated by CocoaTranslator on 10/18/10.
//  Copyright 2010 Interface Ecology Lab. 
//

#import "LogOps.h"

@implementation LogOps

- (void) dealloc {
	[super dealloc];
}



@end

