//
//  LogueMessage.m
//  ecologylabXML
//
//  Generated by CocoaTranslator on 10/18/10.
//  Copyright 2010 Interface Ecology Lab. 
//

#import "LogueMessage.h"

@implementation LogueMessage

@synthesize logName;
- (void) dealloc {
	[logName release];
	[super dealloc];
}



@end

