//
//  MixedInitiativeOp.m
//  ecologylabXML
//
//  Generated by CocoaTranslator on 08/19/10.
//  Copyright 2010 Interface Ecology Lab. 
//

#import "MixedInitiativeOp.h"

@implementation MixedInitiativeOp

@synthesize intensity;
@synthesize invert;
@synthesize action;
@synthesize recordTime;
- (void) dealloc {
	[super dealloc];
	[action release];
}

- (void) setIntensityWithReference: (short *) p_intensity {
	intensity = *p_intensity;
}

- (void) setInvertWithReference: (bool *) p_invert {
	invert = *p_invert;
}

- (void) setRecordTimeWithReference: (long *) p_recordTime {
	recordTime = *p_recordTime;
}



@end

