//
//  Prologue.h
//  ecologylabXML
//
//  Generated by CocoaTranslator on 06/16/10.
//  Copyright 2010 Interface Ecology Lab. 
//

#import <Foundation/Foundation.h>
#import "ElementState.h"


/*!
	@class		Prologue
	@abstract	This class is generated by CocoaTranslator. 
	@discussion	missing java doc comments or could not find the source file.
*/
@interface Prologue : ElementState
{
	/*!
		@var		date
		@abstract	Annotated as : 
					@xml_attribute
		@discussion	missing java doc comments or could not find the source file.
	*/
	NSString *date;

	/*!
		@var		ip
		@abstract	Annotated as : 
					@xml_attribute
		@discussion	missing java doc comments or could not find the source file.
	*/
	NSString *ip;

	/*!
		@var		userID
		@abstract	Annotated as : 
					@xml_attribute
		@discussion	missing java doc comments or could not find the source file.
	*/
	NSString *userID;

	/*!
		@var		questionId
		@abstract	Annotated as : 
					@xml_attribute
		@discussion	missing java doc comments or could not find the source file.
	*/
	NSString *questionId;

	/*!
		@var		studyName
		@abstract	Annotated as : 
					@xml_attribute
		@discussion	missing java doc comments or could not find the source file.
	*/
	NSString *studyName;

	/*!
		@var		questionPath
		@abstract	Annotated as : 
					@xml_attribute
		@discussion	missing java doc comments or could not find the source file.
	*/
	NSString *questionPath;

}

@property (nonatomic, readwrite, retain) NSString *date;
@property (nonatomic, readwrite, retain) NSString *ip;
@property (nonatomic, readwrite, retain) NSString *userID;
@property (nonatomic, readwrite, retain) NSString *questionId;
@property (nonatomic, readwrite, retain) NSString *studyName;
@property (nonatomic, readwrite, retain) NSString *questionPath;


@end

