//
//  SendPrologue.h
//  ecologylabXML
//
//  Generated by CocoaTranslator on 10/18/10.
//  Copyright 2010 Interface Ecology Lab. 
//

#import <Foundation/Foundation.h>
#import "LogueMessage.h"


/*!
	@class		SendPrologue
	@abstract	This class is generated by CocoaTranslator. Annotated as: 
				@simpl_inherit
	@discussion	missing java doc comments or could not find the source file.
*/
@interface SendPrologue : LogueMessage
{
	/*!
		@var		date
		@abstract	Annotated as : 
					@simpl_scalar
		@discussion	missing java doc comments or could not find the source file.
	*/
	NSString *date;

	/*!
		@var		ip
		@abstract	Annotated as : 
					@simpl_scalar
		@discussion	missing java doc comments or could not find the source file.
	*/
	NSString *ip;

	/*!
		@var		userID
		@abstract	Annotated as : 
					@simpl_scalar
		@discussion	missing java doc comments or could not find the source file.
	*/
	NSString *userID;

	/*!
		@var		studyName
		@abstract	Annotated as : 
					@simpl_scalar
		@discussion	missing java doc comments or could not find the source file.
	*/
	NSString *studyName;

	/*!
		@var		performEpilogueNow
		@abstract	Annotated as : 
					@simpl_scalar
		@discussion	missing java doc comments or could not find the source file.
	*/
	bool performEpilogueNow;

}

@property (nonatomic, readwrite, retain) NSString *date;
@property (nonatomic, readwrite, retain) NSString *ip;
@property (nonatomic, readwrite, retain) NSString *userID;
@property (nonatomic, readwrite, retain) NSString *studyName;
@property (nonatomic, readwrite) bool performEpilogueNow;

- (void) setPerformEpilogueNowWithReference: (bool *) p_performEpilogueNow;

@end

