//
//  SendPrologue.m
//  ecologylabXML
//
//  Generated by CocoaTranslator on 10/18/10.
//  Copyright 2010 Interface Ecology Lab. 
//

#import "SendPrologue.h"

@implementation SendPrologue

@synthesize date;
@synthesize ip;
@synthesize userID;
@synthesize studyName;
@synthesize performEpilogueNow;
- (void) dealloc {
	[date release];
	[ip release];
	[userID release];
	[studyName release];
	[super dealloc];
}

- (void) setPerformEpilogueNowWithReference: (bool *) p_performEpilogueNow {
	performEpilogueNow = *p_performEpilogueNow;
}



@end

