#import "SimplTypesScope.h"
#import "ClassD.h"
#import "ClassC.h"
#import "ClassB.h"
#import "ClassA.h"
#import "ClassX.h"

#import <Foundation/Foundation.h>


/*!
	@class		classDTScope
	@abstract	This class is generated by CocoaTranslator. 
	@discussion	missing java doc comments or could not find the source file.
*/
@interface classDTScope : NSObject
{
}

+ (SimplTypesScope *) simplTypesScope;


@end

