#import "SimplTypesScope.h"
#import "Person.h"
#import "Faculty.h"

#import <Foundation/Foundation.h>


/*!
	@class		facultyTScope
	@abstract	This class is generated by CocoaTranslator. 
	@discussion	missing java doc comments or could not find the source file.
*/
@interface facultyTScope : NSObject
{
}

+ (SimplTypesScope *) simplTypesScope;


@end

