#import "SimplTypesScope.h"
#import "ScalarCollection.h"

#import <Foundation/Foundation.h>


/*!
	@class		scalarCollectionTScope
	@abstract	This class is generated by CocoaTranslator. 
	@discussion	missing java doc comments or could not find the source file.
*/
@interface scalarCollectionTScope : NSObject
{
}

+ (SimplTypesScope *) simplTypesScope;


@end

