#import "SimplTypesScope.h"
#import "Person.h"
#import "Student.h"
#import "StudentDirectory.h"

#import <Foundation/Foundation.h>


/*!
	@class		studentDirectoryTScope
	@abstract	This class is generated by CocoaTranslator. 
	@discussion	missing java doc comments or could not find the source file.
*/
@interface studentDirectoryTScope : NSObject
{
}

+ (SimplTypesScope *) simplTypesScope;


@end

