#import "SimplTypesScope.h"
#import "ClassDes.h"
#import "FieldDes.h"
#import "TranslationS.h"

#import <Foundation/Foundation.h>


/*!
	@class		testingMapWithinMapsTScope
	@abstract	This class is generated by CocoaTranslator. 
	@discussion	missing java doc comments or could not find the source file.
*/
@interface testingMapWithinMapsTScope : NSObject
{
}

+ (SimplTypesScope *) simplTypesScope;


@end

