//
//  BasicOp.h
//  ecologylabXML
//
//  Generated by CocoaTranslator on 08/19/10.
//  Copyright 2010 Interface Ecology Lab. 
//

#import <Foundation/Foundation.h>
#import "ElementState.h"


/*!
	@class		BasicOp
	@abstract	This class is generated by CocoaTranslator. Annotated as: 
				@simpl_inherit
	@discussion	missing java doc comments or could not find the source file.
*/
@interface BasicOp : ElementState
{
	/*!
		@var		sessionTime
		@abstract	Annotated as : 
					@simpl_scalar
		@discussion	missing java doc comments or could not find the source file.
	*/
	long sessionTime;

}

@property (nonatomic, readwrite) long sessionTime;

- (void) setSessionTimeWithReference: (long *) p_sessionTime;

@end

