//
//  Epilogue.m
//  ecologylabXML
//
//  Generated by CocoaTranslator on 06/16/10.
//  Copyright 2010 Interface Ecology Lab. 
//

#import "Epilogue.h"

@implementation Epilogue


+ (void) initialize {
	[Epilogue class];
}

- (void) dealloc {
	[super dealloc];
}



@end

