//
//  Logging.h
//  ecologylabXML
//
//  Generated by CocoaTranslator on 06/16/10.
//  Copyright 2010 Interface Ecology Lab. 
//

#import <Foundation/Foundation.h>
#import "ElementState.h"


/*!
	@class		Logging
	@abstract	This class is generated by CocoaTranslator. 
	@discussion	missing java doc comments or could not find the source file.
*/
@interface Logging : ElementState
{
	/*!
		@var		opSequence
		@abstract	Annotated as : 
					@xml_collection
					@xml_scope
		@discussion	missing java doc comments or could not find the source file.
	*/
	NSMutableArray *opSequence;

}

@property (nonatomic, readwrite, retain) NSMutableArray *opSequence;


@end

