//
//  Prologue.m
//  ecologylabXML
//
//  Generated by CocoaTranslator on 06/16/10.
//  Copyright 2010 Interface Ecology Lab. 
//

#import "Prologue.h"

@implementation Prologue

@synthesize date;
@synthesize ip;
@synthesize userID;
@synthesize questionId;
@synthesize studyName;
@synthesize questionPath;

+ (void) initialize {
	[Prologue class];
}

- (void) dealloc {
	[super dealloc];
	[date release];
	[ip release];
	[userID release];
	[questionId release];
	[studyName release];
	[questionPath release];
}



@end

