#import <Foundation/Foundation.h>
#import "ElementState.h"

/*!
 @class		User
 @abstract	This class is generated by CocoaTranslator. Annotated as: 
 @xml_other_tags
 @xml_inherit
 @discussion	missing java doc comments or could not find the source file.
 */
@interface User : ElementState
{
	/*!
	 @var		userKey
	 @abstract	Annotated as : 
	 @xml_attribute
	 @xml_other_tags
	 @discussion	missing java doc comments or could not find the source file.
	 */
	NSString *userKey;
	
	/*!
	 @var		password
	 @abstract	Annotated as : 
	 @xml_attribute
	 @discussion	missing java doc comments or could not find the source file.
	 */
	NSString *password;
	
	/*!
	 @var		level
	 @abstract	Annotated as : 
	 @xml_attribute
	 @discussion	missing java doc comments or could not find the source file.
	 */
	int level;
	
	/*!
	 @var		uid
	 @abstract	Annotated as : 
	 @xml_attribute
	 @discussion	missing java doc comments or could not find the source file.
	 */
	long uid;
	
}

@property (nonatomic,readwrite, retain) NSString *userKey;
@property (nonatomic,readwrite, retain) NSString *password;
@property (nonatomic,readwrite) int level;
@property (nonatomic,readwrite) long uid;

- (void) setLevelWithReference: (int *) p_level;
- (void) setUidWithReference: (long *) p_uid;

+ (id) userWithUserData : (NSString *) p_userKey withPassword : (NSString *) p_password withLevel : (int) p_level withUID : (long) p_uid;
- (id) initWithUserData : (NSString *) p_userKey withPassword : (NSString *) p_password withLevel : (int) p_level withUID : (long) p_uid;

@end

