//
//  SaverState.m
//  ecologylabXML
//
//  Generated by CocoaTranslator on 06/16/10.
//  Copyright 2010 Interface Ecology Lab. 
//

#import "SaverState.h"

@implementation SaverState


+ (void) initialize {
	[SaverState class];
}

- (void) dealloc {
	[super dealloc];
}



@end

