//
//  ClassDescriptor.h
//  ecologylabXML
//
//  Generated by CocoaTranslator on 12/14/11.
//  Copyright 2011 Interface Ecology Lab. 
//

#import <Foundation/Foundation.h>
#import "ClassA.h"
#import "ClassB.h"


/*!
	@class		ClassD
	@abstract	This class is generated by CocoaTranslator. Annotated as: 
				@simpl_inherit
	@discussion	missing java doc comments or could not find the source file.
*/
@interface ClassD : NSObject
{
	/*!
		@var		classA
		@abstract	Annotated as : 
					@simpl_composite
		@discussion	missing java doc comments or could not find the source file.
	*/
	ClassA *classA;

	/*!
		@var		classB
		@abstract	Annotated as : 
					@simpl_composite
		@discussion	missing java doc comments or could not find the source file.
	*/
	ClassB *classB;

}

@property (nonatomic, readwrite, retain) ClassA *classA;
@property (nonatomic, readwrite, retain) ClassB *classB;


@end

