//
//  ClassDescriptor.m
//  ecologylabXML
//
//  Generated by CocoaTranslator on 12/14/11.
//  Copyright 2011 Interface Ecology Lab. 
//

#import "ClassD.h"

@implementation ClassD

@synthesize classA;
@synthesize classB;

- (void) dealloc 
{
	[classA release];
	[classB release];
	[super dealloc];
}



@end

