//
//  ClassDescriptor.m
//  ecologylabXML
//
//  Generated by CocoaTranslator on 12/14/11.
//  Copyright 2011 Interface Ecology Lab. 
//

#import "ClassC.h"

@implementation ClassC

@synthesize u;
@synthesize w;

- (void) dealloc 
{
	[super dealloc];
}

- (void) setUWithReference: (int *) p_u {
	u = *p_u;
}

- (void) setWWithReference: (int *) p_w {
	w = *p_w;
}



@end

