//
//  ClassDescriptor.h
//  ecologylabXML
//
//  Generated by CocoaTranslator on 12/14/11.
//  Copyright 2011 Interface Ecology Lab. 
//

#import <Foundation/Foundation.h>


/*!
	@class		ClassC
	@abstract	This class is generated by CocoaTranslator. Annotated as: 
				@simpl_inherit
	@discussion	missing java doc comments or could not find the source file.
*/
@interface ClassC : NSObject
{
	/*!
		@var		u
		@abstract	Annotated as : 
					@simpl_scalar
		@discussion	missing java doc comments or could not find the source file.
	*/
	int u;

	/*!
		@var		w
		@abstract	Annotated as : 
					@simpl_scalar
		@discussion	missing java doc comments or could not find the source file.
	*/
	int w;

}

@property (nonatomic, readwrite) int u;
@property (nonatomic, readwrite) int w;

- (void) setUWithReference: (int *) p_u;
- (void) setWWithReference: (int *) p_w;

@end

