//
//  ClassDescriptor.m
//  ecologylabXML
//
//  Generated by CocoaTranslator on 12/14/11.
//  Copyright 2011 Interface Ecology Lab. 
//

#import "Faculty.h"

@implementation Faculty

@synthesize designation;

- (void) dealloc 
{
	[designation release];
	[super dealloc];
}

+ (NSObject *) getPopulatedObject;
{
    Faculty* f = [[[Faculty alloc] init] autorelease];
    f.name = @"test";
    f.designation = @"test22";
    
    return f;
}

@end

