//
//  ClassDescriptor.h
//  ecologylabXML
//
//  Generated by CocoaTranslator on 12/14/11.
//  Copyright 2011 Interface Ecology Lab. 
//

#import <Foundation/Foundation.h>


/*!
	@class		PersonDirectory
	@abstract	This class is generated by CocoaTranslator. Annotated as: 
				@simpl_inherit
	@discussion	missing java doc comments or could not find the source file.
*/
@interface PersonDirectory : NSObject
{
	/*!
		@var		persons
		@abstract	Annotated as : 
					@simpl_classes
					@simpl_collection
		@discussion	missing java doc comments or could not find the source file.
	*/
	NSMutableArray *persons;

}

@property (nonatomic, readwrite, retain) NSMutableArray *persons;


@end

