//
//  ClassDescriptor.m
//  ecologylabXML
//
//  Generated by CocoaTranslator on 12/14/11.
//  Copyright 2011 Interface Ecology Lab. 
//

#import "PersonDirectory.h"

@implementation PersonDirectory

@synthesize persons;

- (void) dealloc 
{
	[persons release];
	[super dealloc];
}



@end

