//
//  ClassDescriptor.h
//  ecologylabXML
//
//  Generated by CocoaTranslator on 12/14/11.
//  Copyright 2011 Interface Ecology Lab. 
//

#import <Foundation/Foundation.h>


/*!
	@class		StudentDirectory
	@abstract	This class is generated by CocoaTranslator. Annotated as: 
				@simpl_inherit
	@discussion	missing java doc comments or could not find the source file.
*/
@interface StudentDirectory : NSObject
{
	/*!
		@var		students
		@abstract	Annotated as : 
					@simpl_nowrap
					@simpl_collection
		@discussion	missing java doc comments or could not find the source file.
	*/
	NSMutableArray *students;

	/*!
		@var		test
		@abstract	Annotated as : 
					@simpl_hints
					@simpl_scalar
		@discussion	missing java doc comments or could not find the source file.
	*/
	NSString *test;

}

@property (nonatomic, readwrite, retain) NSMutableArray *students;
@property (nonatomic, readwrite, retain) NSString *test;


@end

