//
//  ClassDescriptor.m
//  ecologylabXML
//
//  Generated by CocoaTranslator on 12/14/11.
//  Copyright 2011 Interface Ecology Lab. 
//

#import "StudentDirectory.h"

@implementation StudentDirectory

@synthesize students;
@synthesize test;

- (void) dealloc 
{
	[students release];
	[test release];
	[super dealloc];
}



@end

