//
//  ClassDescriptor.h
//  ecologylabXML
//
//  Generated by CocoaTranslator on 12/14/11.
//  Copyright 2011 Interface Ecology Lab. 
//

#import <Foundation/Foundation.h>


/*!
	@class		ScalarCollection
	@abstract	This class is generated by CocoaTranslator. Annotated as: 
				@simpl_inherit
	@discussion	missing java doc comments or could not find the source file.
*/
@interface ScalarCollection : NSObject
{
	/*!
		@var		collectionOfIntegers
		@abstract	Annotated as : 
					@simpl_nowrap
					@simpl_collection
		@discussion	missing java doc comments or could not find the source file.
	*/
	NSMutableArray *collectionOfIntegers;

}

@property (nonatomic, readwrite, retain) NSMutableArray *collectionOfIntegers;


@end

