//
//  ClassDescriptor.m
//  ecologylabXML
//
//  Generated by CocoaTranslator on 12/14/11.
//  Copyright 2011 Interface Ecology Lab. 
//

#import "ScalarCollection.h"

@implementation ScalarCollection

@synthesize collectionOfIntegers;

- (void) dealloc 
{
	[collectionOfIntegers release];
	[super dealloc];
}



@end

