//
//  ClassDescriptor.m
//  ecologylabXML
//
//  Generated by CocoaTranslator on 12/14/11.
//  Copyright 2011 Interface Ecology Lab. 
//

#import "ClassDes.h"

@implementation ClassDes

@synthesize tagName;
@synthesize fieldDescriptorsByTagName;

- (void) dealloc 
{
	[tagName release];
	[fieldDescriptorsByTagName release];
	[super dealloc];
}



@end

