//
//  ClassDescriptor.m
//  ecologylabXML
//
//  Generated by CocoaTranslator on 12/14/11.
//  Copyright 2011 Interface Ecology Lab. 
//

#import "FieldDes.h"

@implementation FieldDes

@synthesize fieldName;

- (void) dealloc 
{
	[fieldName release];
	[super dealloc];
}



@end

