//
//  ClassDescriptor.h
//  ecologylabXML
//
//  Generated by CocoaTranslator on 12/14/11.
//  Copyright 2011 Interface Ecology Lab. 
//

#import <Foundation/Foundation.h>


/*!
	@class		TranslationS
	@abstract	This class is generated by CocoaTranslator. Annotated as: 
				@simpl_inherit
	@discussion	missing java doc comments or could not find the source file.
*/
@interface TranslationS : NSObject
{
	/*!
		@var		entriesByTag
		@abstract	Annotated as : 
					@simpl_nowrap
					@simpl_map
		@discussion	missing java doc comments or could not find the source file.
	*/
	NSDictionary *entriesByTag;

}

@property (nonatomic, readwrite, retain) NSDictionary *entriesByTag;


@end

