//
//  ClassDescriptor.m
//  ecologylabXML
//
//  Generated by CocoaTranslator on 12/14/11.
//  Copyright 2011 Interface Ecology Lab. 
//

#import "TranslationS.h"

@implementation TranslationS

@synthesize entriesByTag;

- (void) dealloc 
{
	[entriesByTag release];
	[super dealloc];
}



@end

