//
//  SaverState.h
//  ecologylabXML
//
//  Generated by CocoaTranslator on 06/16/10.
//  Copyright 2010 Interface Ecology Lab. 
//

#import <Foundation/Foundation.h>
#import "ElementState.h"


/*!
	@class		SaverState
	@abstract	This class is generated by CocoaTranslator. Annotated as: 
				@xml_inherit
	@discussion	missing java doc comments or could not find the source file.
*/
@interface SaverState : ElementState


@end

