//
//  AuthenticationListXMLImpl.m
//  ecologylabXML
//
//  Generated by CocoaTranslator on 06/16/10.
//  Copyright 2010 Interface Ecology Lab. 
//

#import "AuthenticationListXMLImpl.h"

@implementation AuthenticationListXMLImpl

@synthesize authList;
@synthesize lastUID;
@synthesize autoSave;

+ (void) initialize {
	[AuthenticationListXMLImpl class];
}

- (void) dealloc {
	[super dealloc];
}

- (void) setLastUIDWithReference: (long *) p_lastUID {
	lastUID = *p_lastUID;
}

- (void) setAutoSaveWithReference: (bool *) p_autoSave {
	autoSave = *p_autoSave;
}



@end

