//
//  Login.h
//  ecologylabXML
//
//  Generated by CocoaTranslator on 06/16/10.
//  Copyright 2010 Interface Ecology Lab. 
//

#import <Foundation/Foundation.h>
#import "RequestMessage.h"
#import "User.h"


/*!
 @class		Login
 @abstract	This class is generated by CocoaTranslator. Annotated as: 
 @xml_inherit
 @discussion	missing java doc comments or could not find the source file.
 */
@interface Login : RequestMessage
{
	/*!
	 @var		entry
	 @abstract	Annotated as : 
	 @xml_nested
	 @discussion	missing java doc comments or could not find the source file.
	 */
	User *entry;
	
}

@property (nonatomic, readwrite, retain) User *entry;



+ (id) loginWithUserObject : (User *) p_entry;
- (id) initWithUserObject : (User *) p_entry;

+ (id) loginWithUserData : (NSString *) p_userKey withPassword : (NSString *) p_password withLevel : (int) p_level withUID : (long) p_uid;

@end

