//
//  CfCollaborationGetSurrogate.m
//  ecologylabXML
//
//  Generated by CocoaTranslator on 10/18/10.
//  Copyright 2010 Interface Ecology Lab. 
//

#import "CfCollaborationGetSurrogate.h"

@implementation CfCollaborationGetSurrogate

@synthesize surrogateSetString;
- (void) dealloc {
	[surrogateSetString release];
	[super dealloc];
}



@end

