//
//  ContinuedHTTPGetRequest.h
//  ecologylabXML
//
//  Generated by CocoaTranslator on 10/18/10.
//  Copyright 2010 Interface Ecology Lab. 
//

#import <Foundation/Foundation.h>
#import "HttpRequest.h"


/*!
	@class		ContinuedHTTPGetRequest
	@abstract	This class is generated by CocoaTranslator. Annotated as: 
				@simpl_inherit
	@discussion	missing java doc comments or could not find the source file.
*/
@interface ContinuedHTTPGetRequest : HttpRequest
{
	/*!
		@var		messageFragment
		@abstract	Annotated as : 
					@simpl_scalar
					@simpl_hints
		@discussion	missing java doc comments or could not find the source file.
	*/
	NSString *messageFragment;

	/*!
		@var		isLast
		@abstract	Annotated as : 
					@simpl_scalar
		@discussion	missing java doc comments or could not find the source file.
	*/
	bool isLast;

}

@property (nonatomic, readwrite, retain) NSString *messageFragment;
@property (nonatomic, readwrite) bool isLast;

- (void) setIsLastWithReference: (bool *) p_isLast;

@end

