//
//  HttpRequest.m
//  ecologylabXML
//
//  Generated by CocoaTranslator on 10/18/10.
//  Copyright 2010 Interface Ecology Lab. 
//

#import "HttpRequest.h"

@implementation HttpRequest

@synthesize okResponseUrl;
@synthesize errorResponseUrl;
- (void) dealloc {
	[okResponseUrl release];
	[errorResponseUrl release];
	[super dealloc];
}



@end

