//
//  IgnoreRequest.h
//  ecologylabXML
//
//  Generated by CocoaTranslator on 10/18/10.
//  Copyright 2010 Interface Ecology Lab. 
//

#import <Foundation/Foundation.h>
#import "RequestMessage.h"


/*!
	@class		IgnoreRequest
	@abstract	This class is generated by CocoaTranslator. Annotated as: 
				@simpl_inherit
	@discussion	missing java doc comments or could not find the source file.
*/
@interface IgnoreRequest : RequestMessage
{
}



@end

