//
//  PingRequest.m
//  ecologylabXML
//
//  Generated by CocoaTranslator on 10/18/10.
//  Copyright 2010 Interface Ecology Lab. 
//

#import "PingRequest.h"

@implementation PingRequest

- (void) dealloc {
	[super dealloc];
}



@end

