//
//  UrlMessage.m
//  ecologylabXML
//
//  Generated by CocoaTranslator on 10/18/10.
//  Copyright 2010 Interface Ecology Lab. 
//

#import "UrlMessage.h"

@implementation UrlMessage

@synthesize url;
@synthesize collection;
- (void) dealloc {
	[url release];
	[collection release];
	[super dealloc];
}



@end

